[project]
name = 'Interdimensional-Supply-Chain-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.multiversal-customs-tariff]
path = 'contracts/multiversal-customs-tariff.clar'
clarity_version = 2
epoch = 2.5

[contracts.reality-agnostic-logistics]
path = 'contracts/reality-agnostic-logistics.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
